#???
spring:
  application:
    name: zake-code-mother-backend
#??
server:
  port: 8123
#  ??
  servlet:
    context-path: /api
#swagger
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.zake.aicode.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
